# For VS Code
library(languageserver)
library(httpgd)
# Used packages
library(conflicted)
library(commonmark)
library(dotenv)
library(dplyr)
library(gargle)
library(glue)
library(googledrive)
library(googlesheets4)
library(knitr)
library(kableExtra)
library(rmarkdown)
library(scales)
library(scholar)
library(sodium)
library(stringR)
library(targets)
library(tarchetypes)
library(vitae)
library(wosr)